repos:
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black --check
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: system
        name: Pylint
        entry: poetry run pylint
        language: system
        types: [python]
